[project]
name = "zk-previewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.0",
    "watchdog>=6.0.0",
]
